INSERT INTO Position (PositionName)
VALUES(
'N/A'
,'Temp DP Receptionist'
,'Temp DP Kitchen Asst.'
,'Peer Support Specialist'
,'Residential Senior Housing Aide'
,'Residential Aide'
,'Support Specialist'
,'Medical Assistant'
,'2nd Yr. Ph.D. Student'
,'1st Yr. Ph.D. Student'
,'Masters Student'
,'Bachelors Student'
,'Case Manager I'
,'Case Manager II'
,'Utilization Coordinator'
,'Family Facilitator'
,'Clinical Support Specialist'
,'Clinical Secretary'
,'Contract Specialist'
,'Administrative Assistant to Pres/CEO'
,'Information Systems/Support Specialist'
,'Masters - Unlicensed'
,'Masters - Licensed'
,'Psychologist - Unlicensed'
,'Psychologist - Licensed'
,'Accountant - B.S.'
,'Accountant - M.A NO CPA'
,'Accountant - M.A. CPA'
,'LPN Nurse'
,'RN'
,'APRN'
,'Psychiatrist'
,'Programmer'
,'Senior Network Administrator'
,'Corporate Compliance Officer'
,'Director of H/R and MIS'
,'Director of Financial Services'
,'President/CEO');